pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git url: 'https://github.com/pala3232/testtodo.git', branch: 'main'
            }
        }
        stage('Install Requirements') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install -r requirements.txt'
            }
        }
        stage('Bandit check') {
            steps {
                sh './venv/bin/bandit -r . -lll -f txt -o bandit.txt'
            }
        }
    }
    post {
        always {
         archiveArtifacts artifacts: 'bandit.txt', allowEmptyArchive: true
   }
  }
}